USE MASTER ;
IF BD_ID('SELLER') IS NOT NULL
    DROP DATABASE SELLER;
CREATE DATABASE SELLER;
IF OBJECT_ID('PRODUCTS') IS NOT NULL
    DROP TABLE PRODUCTS
CREATE TABLE SELLER.PRODUCTS(
    NAME_OF_PRODEUCT NVARCHAR(20) PRIMARY KEY,
    PRICE REAL NOT NULL,
    COUN_OF_PRODUCTS INT NOT NULL
);
IF OBJECT_ID('CUSTOMERS') IS NOT NULL
    DROP TABLE SELLER.CUSTOMERS;
CREATE TABLE CUSTOMER(
    NAME_OF_CUSTOMER NVARCHAR(20) PRIMARY KEY,
    ADRES NVARCHAR(50) NOT NULL,
    CHEKING_ACCOUNT NVARCHAR(15) NOT NULL
);
IF OBJECT_ID('ORDERS') IS NOT NULL
    DROP TABLE ORDERS;
CREATE TABLE SELLER.ORDERS( 
    NUMBER_OF_ORDER NVARCHAR(10) PRIMARY KEY,
    NAME_OF_PRODUCT NVARCHAR(20) NOT NULL,
    PRICE REAL NOT NULL,
    COUNT INT NOT NULL,
    DATE_OF_DILIVERY DATE NOT NULL,
    CUSTOMER NVARCHAR(20) NOT NULL
);
